# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='vimeo_id',
            field=models.CharField(default='empty', max_length=50),
            preserve_default=False,
        ),
    ]
