# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20160822_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vimeo_id',
            field=models.CharField(max_length=50, verbose_name='Vimeo ID'),
        ),
    ]
