# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20160822_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='song',
            field=models.CharField(default='emptyyyy', max_length=200),
            preserve_default=False,
        ),
    ]
