# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20160822_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vimeo_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Vimeo ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name=b'YouTube ID'),
        ),
    ]
