# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20160824_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='video',
            name='song',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='vimeo_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vimeo ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='YouTube ID'),
        ),
    ]
